Repository moodlehq/moodle-cs, pull requests merged in 2024-02, with the labels that each got.

#105 Discard non-variables within double quoted strings
  moodle/Sniffs/NamingConventions/ValidVariableNameSniff.php
  moodle/Tests/MoodleStandardTest.php
  moodle/Tests/fixtures/moodle_namingconventions_variablename.php
  moodle/Tests/fixtures/moodle_namingconventions_variablename.php.fixed
Labels: bug

#100 Avoid PHP error with BoilerplateComment and empty files
  moodle/Sniffs/Files/BoilerplateCommentSniff.php
  moodle/Tests/FilesBoilerPlateCommentTest.php
  moodle/Tests/fixtures/files/boilerplatecomment/short_empty.php
Labels: bug

#104 Check for correct whitespace in method declarations
  moodle/Sniffs/Methods/MethodDeclarationSpacingSniff.php
  moodle/Tests/MoodleStandardTest.php
  moodle/Tests/Sniffs/Methods/MethodDeclarationSpacingSniffTest.php
  moodle/Tests/fixtures/Methods/MethodDeclarationSpacing.php
  moodle/Tests/fixtures/Methods/MethodDeclarationSpacing.php.fixed
  moodle/Tests/fixtures/psr12_functions_nullabletypedeclaration.php
  moodle/Tests/fixtures/psr12_functions_nullabletypedeclaration.php.fixed
  moodle/Tests/fixtures/psr12_functions_returntypedeclaration.php
  moodle/Tests/fixtures/psr12_functions_returntypedeclaration.php.fixed
  moodle/ruleset.xml
Labels: enhancement

#103 Unit test classes should be declared as either final or abstract
  moodle/Sniffs/PHPUnit/TestCasesAbstractSniff.php
  moodle/Sniffs/PHPUnit/TestClassesFinalSniff.php
  moodle/Tests/Sniffs/PHPUnit/TestClassesFinalSniffTest.php
  moodle/Tests/Sniffs/PHPUnit/TestcaseAbstractSniffTest.php
  moodle/Tests/Sniffs/PHPUnit/fixtures/testcaseclassesabstract.php
  moodle/Tests/Sniffs/PHPUnit/fixtures/testcaseclassesabstract.php.fixed
  moodle/Tests/Sniffs/PHPUnit/fixtures/testclassesfinal.php
  moodle/Tests/Sniffs/PHPUnit/fixtures/testclassesfinal.php.fixed
Labels: enhancement

#108 Revert "Downgrade code to be PHP 7.0 compliant."
  moodle/Util/MoodleUtil.php
Labels: enhancement

#109 Bump squizlabs/php_codesniffer to 3.9.0
  CHANGELOG.md
  composer.json
Labels: task
